blank_issues_enabled: false
contact_links:
  - name: 💬 社群讨论
    url: https://qm.qq.com/q/DQwCftuBJ6
    about: 一般性问题、想法交流请在社群进行讨论
  - name: 📖 项目文档
    url: https://ccnlf8xcz6k3.feishu.cn/wiki/AluRw6wyZijyOEk3RCjcWAlon8c
    about: 查看项目文档获取更多信息
